name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./explore_buddy
          # dockerfile: ./Dockerfile
          push: true
          tags: tavco/project-kiii-backend:latest
      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          # dockerfile: ./Dockerfile
          push: true
          tags: tavco/project-kiii-client:latest
